name: Verify Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"
  merge_group:
    types:
      - checks_requested
  push:
    branches:
      - main

permissions:
  contents: read
  #packages: write

jobs:
  # Pre-emptively added for future buildout  
  workflow_changes:
    with:
      what_to_check: ./.github
    uses: ./.github/workflows/checkForChanges.yml

  service_changes:
    with:
      what_to_check: ./HarborIntegrationService
    uses: ./.github/workflows/checkForChanges.yml

  dockerfile_changes:
    with:
      what_to_check: ./HarborIntegrationService/Dockerfile
    uses: ./.github/workflows/checkForChanges.yml
    

  build_service:
    needs:
      - service_changes
    if: needs.service_changes.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10"
      - name: Restore NuGet packages
        working-directory: ./HarborIntegrationService
        run: dotnet restore
      - name: Build service
        working-directory: ./HarborIntegrationService
        run: dotnet build
    
  build_docker:
    needs:
      - dockerfile_changes
      - service_changes
    if: needs.dockerfile_changes.outputs.has_changes == 'true' || needs.service_changes.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Set up Docker
        uses: docker/setup-docker-action@v5
      - name: Build service container
        working-directory: ./HarborIntegrationService
        run: docker build .