{
 "title": "nbs-prometheus-metrics-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=~\"[4-5].*\"}[2m]))",
     "legendFormat": "errors/2m"
    }
   ]
  },
  {
   "title": "Total Request Volume ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[2m]))",
     "legendFormat": "requests/2m"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])*1000))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.90,sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])*1000))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.95,sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[5m])*1000))",
     "legendFormat": "95th percentile"
    }
   ]
  }
 ]
}